// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battle.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "battle.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace message {

namespace {

const ::google::protobuf::EnumDescriptor* AliveState_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ObjAttributeInt_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* MoveObjAttributeInt_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* UnitAttributeInt_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_battle_2eproto() {
  protobuf_AddDesc_battle_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "battle.proto");
  GOOGLE_CHECK(file != NULL);
  AliveState_descriptor_ = file->enum_type(0);
  ObjAttributeInt_descriptor_ = file->enum_type(1);
  MoveObjAttributeInt_descriptor_ = file->enum_type(2);
  UnitAttributeInt_descriptor_ = file->enum_type(3);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_battle_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_battle_2eproto() {
}

void protobuf_AddDesc_battle_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014battle.proto\022\007message*7\n\nAliveState\022\024\n"
    "\020AliveState_Alive\020\001\022\023\n\017AliveState_Dead\020\002"
    "*<\n\017ObjAttributeInt\022\016\n\nALiveState\020\000\022\014\n\010A"
    "Faction\020\001\022\013\n\007AObjMax\020\002*6\n\023MoveObjAttribu"
    "teInt\022\016\n\nAMoveSpeed\020\000\022\017\n\013AMoveObjMax\020\001*\230"
    "\001\n\020UnitAttributeInt\022\n\n\006AMaxHp\020\000\022\007\n\003AHp\020\001"
    "\022\r\n\tAManaType\020\002\022\014\n\010AMaxMana\020\003\022\t\n\005AMana\020\004"
    "\022\r\n\tARunSpeed\020\005\022\016\n\nAWalkSpeed\020\006\022\014\n\010ADefe"
    "nce\020\007\022\014\n\010AShardCD\020\010\022\014\n\010AUnitMax\020\t", 353);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "battle.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_battle_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_battle_2eproto {
  StaticDescriptorInitializer_battle_2eproto() {
    protobuf_AddDesc_battle_2eproto();
  }
} static_descriptor_initializer_battle_2eproto_;
const ::google::protobuf::EnumDescriptor* AliveState_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AliveState_descriptor_;
}
bool AliveState_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ObjAttributeInt_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ObjAttributeInt_descriptor_;
}
bool ObjAttributeInt_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* MoveObjAttributeInt_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MoveObjAttributeInt_descriptor_;
}
bool MoveObjAttributeInt_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* UnitAttributeInt_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UnitAttributeInt_descriptor_;
}
bool UnitAttributeInt_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)
